version: '3.8'

services:
  banknote-checker:
    image: node:18-alpine
    container_name: banknote-price-checker
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    command: sh -c "npm ci && npm start"
    restart: "no"
